import { Site, Notification } from '@/types';

export const mockSites: Site[] = [
  {
    id: '1',
    name: 'Sweet Delights Bakery',
    domain: 'sweetdelights.com',
    status: 'live',
    plan: 'Pro Plan',
    siteType: 'WordPress',
    visits: 12847,
    lastUpdated: '2 hours ago',
    hasSSL: true,
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
  },
  {
    id: '2',
    name: 'TechStart Solutions',
    domain: 'techstart.io',
    status: 'live',
    plan: 'Business Plan',
    siteType: 'Static HTML',
    visits: 8432,
    lastUpdated: '5 hours ago',
    hasSSL: true,
    thumbnail: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg',
  },
  {
    id: '3',
    name: 'Brew Haven Coffee',
    domain: 'brewhaven.com',
    status: 'deploying',
    plan: 'Pro Plan',
    siteType: 'WordPress',
    visits: 5691,
    lastUpdated: '1 day ago',
    hasSSL: true,
  },
  {
    id: '4',
    name: 'FitCore Gym',
    domain: 'fitcore.fitness',
    status: 'live',
    plan: 'Starter Plan',
    siteType: 'Static HTML',
    visits: 3248,
    lastUpdated: '3 days ago',
    hasSSL: true,
  },
  {
    id: '5',
    name: 'Radiance Beauty Spa',
    domain: 'radiance-spa.com',
    status: 'paused',
    plan: 'Pro Plan',
    siteType: 'WordPress',
    visits: 6142,
    lastUpdated: '1 week ago',
    hasSSL: false,
  },
  {
    id: '6',
    name: 'Sterling Legal Group',
    domain: 'sterlinglegal.law',
    status: 'live',
    plan: 'Business Plan',
    siteType: 'WordPress',
    visits: 9873,
    lastUpdated: '4 hours ago',
    hasSSL: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'deployment',
    title: 'Deployment Successful',
    message: 'Sweet Delights Bakery deployed to production successfully',
    timestamp: '2m ago',
    isRead: false,
    icon: { type: 'success', color: 'green' },
  },
  {
    id: '2',
    type: 'domain',
    title: 'Domain Connected',
    message: 'brewhaven.com has been successfully connected and SSL certificate issued',
    timestamp: '15m ago',
    isRead: false,
    icon: { type: 'info', color: 'blue' },
  },
  {
    id: '3',
    type: 'deployment',
    title: 'Deployment Failed',
    message: 'FitCore Gym staging deployment failed due to build error',
    timestamp: '1h ago',
    isRead: false,
    icon: { type: 'error', color: 'red' },
  },
  {
    id: '4',
    type: 'security',
    title: 'Security Alert',
    message: 'Unusual login attempt detected from new location for TechFlow Solutions',
    timestamp: '2h ago',
    isRead: false,
    icon: { type: 'warning', color: 'amber' },
  },
  {
    id: '5',
    type: 'general',
    title: 'AI Content Generated',
    message: 'Hero and About sections generated for Radiance Beauty Spa',
    timestamp: '3h ago',
    isRead: false,
    icon: { type: 'info', color: 'purple' },
  },
  {
    id: '6',
    type: 'domain',
    title: 'DNS Propagation Pending',
    message: 'techflow.io DNS changes are propagating. SSL will be issued once complete',
    timestamp: '4h ago',
    isRead: false,
    icon: { type: 'warning', color: 'amber' },
  },
  {
    id: '7',
    type: 'billing',
    title: 'Payment Successful',
    message: 'Your monthly subscription of $247 has been processed successfully',
    timestamp: '1d ago',
    isRead: false,
    icon: { type: 'success', color: 'emerald' },
  },
  {
    id: '8',
    type: 'security',
    title: 'Firewall Configuration Alert',
    message: 'Sterling Legal Group has an outdated firewall rule set',
    timestamp: '1d ago',
    isRead: false,
    icon: { type: 'error', color: 'red' },
  },
];
