export interface Theme {
  id: string;
  name: string;
  description: string;
  category: string;
  platform: string;
  rating: number;
  downloads: string;
  purchasedDate: string;
  gradient: string;
  icon: string;
  tags: string[];
  pages: string;
  responsive: boolean;
}

export const themes: Theme[] = [
  {
    id: 'corporate-pro',
    name: 'Corporate Pro',
    description: 'Professional business theme',
    category: 'Business',
    platform: 'WordPress',
    rating: 4.9,
    downloads: '2.4k',
    purchasedDate: '2 weeks ago',
    gradient: 'from-blue-500 to-purple-600',
    icon: 'fa-briefcase',
    tags: ['Business', 'WordPress', 'Responsive'],
    pages: '15+',
    responsive: true,
  },
  {
    id: 'shop-master',
    name: 'ShopMaster',
    description: 'Modern e-commerce solution',
    category: 'E-Commerce',
    platform: 'WordPress',
    rating: 4.8,
    downloads: '1.8k',
    purchasedDate: '1 month ago',
    gradient: 'from-green-500 to-teal-600',
    icon: 'fa-store',
    tags: ['E-Commerce', 'WordPress', 'Responsive'],
    pages: '20+',
    responsive: true,
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    description: 'Showcase your work beautifully',
    category: 'Portfolio',
    platform: 'HTML/CSS',
    rating: 5.0,
    downloads: '3.2k',
    purchasedDate: '3 weeks ago',
    gradient: 'from-purple-500 to-pink-600',
    icon: 'fa-image',
    tags: ['Portfolio', 'HTML/CSS', 'Responsive'],
    pages: '12+',
    responsive: true,
  },
  {
    id: 'restaurant-deluxe',
    name: 'Restaurant Deluxe',
    description: 'Perfect for food businesses',
    category: 'Restaurant',
    platform: 'WordPress',
    rating: 4.7,
    downloads: '1.5k',
    purchasedDate: '5 days ago',
    gradient: 'from-orange-500 to-red-600',
    icon: 'fa-utensils',
    tags: ['Restaurant', 'WordPress', 'Responsive'],
    pages: '10+',
    responsive: true,
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    description: 'Modern SaaS landing page',
    category: 'Business',
    platform: 'React',
    rating: 4.9,
    downloads: '2.1k',
    purchasedDate: '1 week ago',
    gradient: 'from-cyan-500 to-blue-600',
    icon: 'fa-rocket',
    tags: ['Business', 'React', 'Responsive'],
    pages: '8+',
    responsive: true,
  },
  {
    id: 'agency-pro',
    name: 'Agency Pro',
    description: 'Creative agency showcase',
    category: 'Agency',
    platform: 'Vue',
    rating: 4.8,
    downloads: '1.9k',
    purchasedDate: '2 months ago',
    gradient: 'from-indigo-500 to-purple-600',
    icon: 'fa-users',
    tags: ['Agency', 'Vue', 'Responsive'],
    pages: '14+',
    responsive: true,
  },
  {
    id: 'wedding-bliss',
    name: 'Wedding Bliss',
    description: 'Elegant wedding website',
    category: 'Events',
    platform: 'HTML/CSS',
    rating: 5.0,
    downloads: '2.7k',
    purchasedDate: '3 months ago',
    gradient: 'from-rose-500 to-pink-600',
    icon: 'fa-heart',
    tags: ['Events', 'HTML/CSS', 'Responsive'],
    pages: '6+',
    responsive: true,
  },
  {
    id: 'magazine-modern',
    name: 'Magazine Modern',
    description: 'Content-rich blog theme',
    category: 'Blog',
    platform: 'WordPress',
    rating: 4.6,
    downloads: '1.3k',
    purchasedDate: '6 weeks ago',
    gradient: 'from-amber-500 to-orange-600',
    icon: 'fa-newspaper',
    tags: ['Blog', 'WordPress', 'Responsive'],
    pages: '18+',
    responsive: true,
  },
  {
    id: 'fitness-hub',
    name: 'Fitness Hub',
    description: 'Gym and fitness center theme',
    category: 'Health',
    platform: 'HTML/CSS',
    rating: 4.7,
    downloads: '1.6k',
    purchasedDate: '4 weeks ago',
    gradient: 'from-teal-500 to-green-600',
    icon: 'fa-dumbbell',
    tags: ['Health', 'HTML/CSS', 'Responsive'],
    pages: '12+',
    responsive: true,
  },
  {
    id: 'music-studio',
    name: 'Music Studio',
    description: 'For musicians and bands',
    category: 'Music',
    platform: 'WordPress',
    rating: 4.9,
    downloads: '2.0k',
    purchasedDate: '1 month ago',
    gradient: 'from-violet-500 to-purple-600',
    icon: 'fa-music',
    tags: ['Music', 'WordPress', 'Responsive'],
    pages: '10+',
    responsive: true,
  },
  {
    id: 'education-pro',
    name: 'Education Pro',
    description: 'Online courses and learning',
    category: 'Education',
    platform: 'React',
    rating: 4.8,
    downloads: '1.7k',
    purchasedDate: '2 weeks ago',
    gradient: 'from-sky-500 to-blue-600',
    icon: 'fa-graduation-cap',
    tags: ['Education', 'React', 'Responsive'],
    pages: '16+',
    responsive: true,
  },
  {
    id: 'spa-wellness',
    name: 'Spa & Wellness',
    description: 'Relaxation and beauty services',
    category: 'Health',
    platform: 'HTML/CSS',
    rating: 4.9,
    downloads: '1.4k',
    purchasedDate: '3 weeks ago',
    gradient: 'from-emerald-500 to-teal-600',
    icon: 'fa-spa',
    tags: ['Health', 'HTML/CSS', 'Responsive'],
    pages: '9+',
    responsive: true,
  },
];

export const themeFeatures = [
  {
    id: 1,
    icon: 'fa-mobile-screen-button',
    title: 'Fully Responsive',
    description: 'Looks perfect on all devices from mobile to desktop with adaptive layouts.',
    color: 'blue',
  },
  {
    id: 2,
    icon: 'fa-wand-magic-sparkles',
    title: 'AI-Ready',
    description: 'Seamlessly integrate AI content generation for text, images, and layouts.',
    color: 'purple',
  },
  {
    id: 3,
    icon: 'fa-gauge-high',
    title: 'Optimized Performance',
    description: 'Lightning-fast loading times with optimized code and best practices.',
    color: 'green',
  },
  {
    id: 4,
    icon: 'fa-shield-halved',
    title: 'Security Built-in',
    description: 'Enterprise-grade security features and SSL certificates included.',
    color: 'orange',
  },
  {
    id: 5,
    icon: 'fa-palette',
    title: 'Easy Customization',
    description: 'Customize colors, fonts, and layouts without touching code.',
    color: 'red',
  },
  {
    id: 6,
    icon: 'fa-magnifying-glass',
    title: 'SEO Optimized',
    description: 'Built with SEO best practices to help your site rank better.',
    color: 'teal',
  },
  {
    id: 7,
    icon: 'fa-code',
    title: 'Clean Code',
    description: 'Well-documented, maintainable code following industry standards.',
    color: 'indigo',
  },
  {
    id: 8,
    icon: 'fa-headset',
    title: 'Premium Support',
    description: 'Access to dedicated support team and comprehensive documentation.',
    color: 'pink',
  },
];

export const popularThemes = [
  {
    id: 'corporate-pro',
    name: 'Corporate Pro',
    description: 'Most deployed theme this month with 247 new sites launched.',
    rating: 4.9,
    downloads: '2.4k',
    rank: 1,
    gradient: 'from-blue-50 to-blue-100',
    borderColor: 'border-blue-200',
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    description: 'Trending among designers with 189 deployments this month.',
    rating: 5.0,
    downloads: '3.2k',
    rank: 2,
    gradient: 'from-purple-50 to-purple-100',
    borderColor: 'border-purple-200',
  },
  {
    id: 'shop-master',
    name: 'ShopMaster',
    description: 'E-commerce favorite with 156 stores launched this month.',
    rating: 4.8,
    downloads: '1.8k',
    rank: 3,
    gradient: 'from-green-50 to-green-100',
    borderColor: 'border-green-200',
  },
];

export const categories = [
  'All Categories',
  'Business',
  'E-Commerce',
  'Portfolio',
  'Blog',
  'Restaurant',
  'Agency',
  'Events',
  'Health',
  'Music',
  'Education',
];

export const platforms = [
  'All Platforms',
  'WordPress',
  'HTML/CSS',
  'React',
  'Vue',
];
